console.log("Hello Yaakov");
console.log("Good Bye John");
console.log("Good Bye Jen");
console.log("Hello Paul");
console.log("Hello Frank");
console.log("Hello Larry");
console.log("Hello Paula");
console.log("Hello Laura");
console.log("Good Bye Jim");
console.log(`20 * 56 = ${20 * 56}`);
